### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Heyian** [Heyian/pre-commit-php#1]
Things to implement

- [x] Add Pest as the testing suite
- [x] Add Sail as the development environment
- [ ] Better document Sail implementation
- [x] Add parallel testing in Pest
- [ ] Refactor parallel testing to use the option only if parallel testing is installed
- [ ] Clean Pest file
